"use client";
import { useCallback, useEffect, useState } from "react";
import { authenticatedFetch } from "./marketplace-client";

type Statement = { period: { start: string; end: string; vendorId: number | null }; accounts: Array<{ accountCode: string; name: string; accountType: string; debitPaise: number; creditPaise: number; balancePaise: number }>; trialBalance: { totalDebits: number; totalCredits: number; balanced: boolean }; profitAndLoss: { incomePaise: number; expensePaise: number; netIncomePaise: number }; balanceSheet: { assetsPaise: number; liabilitiesPaise: number; equityPaise: number; balanced: boolean } };
const money = (paise: number) => `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

export function AccountingStatements({ vendor }: { vendor?: boolean }) {
  const [data, setData] = useState<Statement | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { setError(""); const response = await authenticatedFetch(vendor ? "/api/vendor/accounting" : "/api/admin/accounting", { cache: "no-store" }); const payload = await response.json() as Statement & { error?: string }; if (!response.ok) { setError(payload.error || "Accounting statements are unavailable"); return; } setData(payload); }, [vendor]);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  if (error) return <section className="portal-panel"><h2>Accounting statements</h2><p>{error}</p><button className="portal-outline" onClick={() => void load()} type="button">Retry</button></section>;
  if (!data) return <section className="portal-panel"><h2>Accounting statements</h2><p>Loading governed ledger statements…</p></section>;
  return <div className="portal-stack"><section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">DOUBLE-ENTRY ACCOUNTING</span><h2>Trial balance, P&amp;L and balance sheet</h2><p>{data.period.start} to {data.period.end}. Values are derived from immutable postings and opening balances.</p></div><button className="portal-outline" onClick={() => void load()} type="button">Refresh</button></div><div className="balance-grid"><article><small>Trial balance</small><strong>{data.trialBalance.balanced ? "Balanced" : "Exception"}</strong><span>Debits <b>{money(data.trialBalance.totalDebits)}</b></span><span>Credits <b>{money(data.trialBalance.totalCredits)}</b></span></article><article><small>Profit &amp; loss</small><strong>{money(data.profitAndLoss.netIncomePaise)}</strong><span>Income <b>{money(data.profitAndLoss.incomePaise)}</b></span><span>Expenses <b>{money(data.profitAndLoss.expensePaise)}</b></span></article><article className="equity"><small>Balance sheet</small><strong>{data.balanceSheet.balanced ? "Balanced" : "Exception"}</strong><span>Assets <b>{money(data.balanceSheet.assetsPaise)}</b></span><span>Liabilities + equity <b>{money(data.balanceSheet.liabilitiesPaise + data.balanceSheet.equityPaise)}</b></span></article></div></section><section className="portal-panel"><div className="portal-panel-heading"><div><h2>Chart of accounts</h2><p>Account-level drilldown with normal-balance presentation.</p></div></div><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{data.accounts.map((account) => <tr key={account.accountCode}><td><strong>{account.accountCode}</strong></td><td>{account.name}</td><td>{account.accountType}</td><td>{money(account.debitPaise)}</td><td>{money(account.creditPaise)}</td><td>{money(account.balancePaise)}</td></tr>)}</tbody></table></div></section></div>;
}
