"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { AlertTriangle, BellRing, Boxes, CheckCircle2, FileCheck2, Landmark, Plus, RefreshCw, ShieldCheck, Thermometer, Truck } from "lucide-react";
import { accessToken, authenticatedFetch } from "./marketplace-client";
import { nextRiderAction } from "../lib/operations-controls";
import { GeoLocationPicker } from "./geo-location-picker";

function Notice({ error, message }: { error: string; message: string }) {
  return <>{message && <div className="auth-message success">{message}</div>}{error && <div className="auth-message error">{error}</div>}</>;
}

type SafetyData = { reminders: Array<{id:number;medicineName:string;dosageInstructions:string;reminderTime:string;startDate:string;endDate:string|null;recurrenceRule:string;active:number}>; consents:Array<{purpose:string;consentStatus:string}>; notifications:Array<{id:number;title:string;message:string;readAt:string|null;createdAt:string}>; policyVersion:string };
export function CustomerSafetyCenter() {
  const [data,setData]=useState<SafetyData|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[signedIn,setSignedIn]=useState(false);
  const load=async()=>{setError(""); const token=await accessToken();setSignedIn(Boolean(token));if(!token){setData(null);return;}const response=await authenticatedFetch("/api/customer/safety",{cache:"no-store"});const payload=await response.json() as SafetyData&{error?:string};if(!response.ok){setError(payload.error||"Safety settings could not be loaded");return;}setData(payload);};
  useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load();},[]);
  const post=async(payload:Record<string,unknown>)=>{setError("");setMessage("");const response=await authenticatedFetch("/api/customer/safety",{method:"POST",body:JSON.stringify(payload)});const body=await response.json() as {error?:string};if(!response.ok){setError(body.error||"Update failed");return;}setMessage("Saved securely with an audit record.");await load();};
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const values=new FormData(event.currentTarget);void post({action:"create_reminder",medicineName:values.get("medicineName"),dosageInstructions:values.get("dosageInstructions"),reminderTime:values.get("reminderTime"),startDate:values.get("startDate"),endDate:values.get("endDate"),recurrenceRule:values.get("recurrenceRule")});event.currentTarget.reset();};
  const consent=(purpose:string)=>data?.consents.find(row=>row.purpose===purpose)?.consentStatus==="granted";
  return <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">MEDICATION SAFETY & PRIVACY</span><h2>Pill schedule and consent controls</h2><p>Customers control each reminder and purpose-specific consent. Every change is audit logged.</p></div><button className="portal-outline" onClick={()=>void load()} type="button"><RefreshCw size={15}/> Refresh</button></div>
    {!signedIn&&<div className="refill-empty"><BellRing size={20}/><span><strong>Sign in with the test customer</strong><small>Create schedules and manage privacy consent after authentication.</small></span></div>}<Notice error={error} message={message}/>
    {signedIn&&<><div className="portal-split"><div><h3>Medication schedule</h3><form className="portal-form-grid one" onSubmit={submit}><label className="portal-field"><span>Medicine *</span><input name="medicineName" required/></label><label className="portal-field"><span>Dosage instructions</span><input name="dosageInstructions" placeholder="e.g. one tablet after food"/></label><label className="portal-field"><span>Reminder time *</span><input name="reminderTime" required type="time"/></label><label className="portal-field"><span>Start date *</span><input name="startDate" required type="date"/></label><label className="portal-field"><span>End date</span><input name="endDate" type="date"/></label><label className="portal-field"><span>Repeat</span><select name="recurrenceRule"><option value="daily">Daily</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option></select></label><button className="portal-primary" type="submit"><Plus size={15}/> Add reminder</button></form><div className="history-cards">{data?.reminders.map(row=><article key={row.id}><span><BellRing size={18}/></span><div><strong>{row.medicineName} · {row.reminderTime}</strong><small>{row.dosageInstructions||"No dosage note"}</small><em>{row.startDate}{row.endDate?` to ${row.endDate}`:""} · {row.recurrenceRule}</em></div><button onClick={()=>void post({action:"toggle_reminder",id:row.id,active:!row.active})} type="button">{row.active?"Pause":"Enable"}</button></article>)}</div></div>
      <div><h3>Purpose-specific consent</h3><p className="secure-recovery-note"><ShieldCheck size={16}/> Policy {data?.policyVersion}. Essential fulfilment remains separate from optional reminders and marketing.</p>{[["order_fulfilment","Order fulfilment"],["prescription_processing","Prescription processing"],["health_reminders","Health reminders"],["marketing","Marketing messages"]].map(([purpose,label])=><article className="portal-note" key={purpose}><ShieldCheck size={18}/><span><strong>{label}</strong><small>{consent(purpose)?"Granted — you may withdraw":"Not granted / withdrawn"}</small></span><button className="portal-outline" onClick={()=>void post({action:"consent",purpose,granted:!consent(purpose)})} type="button">{consent(purpose)?"Withdraw":"Grant"}</button></article>)}</div></div><div className="history-cards"><h3>Notification inbox</h3>{data?.notifications.map(row=><article key={row.id}><span><BellRing size={18}/></span><div><strong>{row.title}</strong><small>{row.message}</small><em>{row.createdAt.slice(0,16).replace("T"," ")}{row.readAt?" · Read":" · New"}</em></div>{!row.readAt&&<button onClick={()=>void post({action:"read_notification",id:row.id})} type="button">Mark read</button>}</article>)}</div></>}
  </section>;
}

type VendorOps={summary:{lowStock:number;nearExpiry:number;quarantined:number;onlineSalesPaise:number;offlineSalesPaise:number};alerts:Array<{id:number;productName:string;batchNumber:string;expiryDate:string;quantity:number;alertType:string}>;sales:Array<{saleDate:string;channel:string;transactions:number;totalPaise:number}>;inventory:Array<{id:number;productName:string;batchNumber:string;expiryDate:string;quantity:number;storageLocation:string;coldChainRequired:number;quarantineStatus:string}>;returns:Array<{returnNumber:string;creditNoteNumber:string;refundPaise:number;reason:string;createdAt:string}>;supplierReturns:Array<{returnNumber:string;debitNoteNumber:string;totalPaise:number;reason:string;supplierName:string;purchaseNumber:string}>;returnablePurchases:Array<{purchaseOrderItemId:number;productName:string;batchNumber:string;purchaseNumber:string;supplierName:string;currentQuantity:number;returnedQuantity:number;purchasedQuantity:number}>;temperatures:Array<{id:number;productName:string;batchNumber:string;temperatureCelsiusX10:number;withinRange:number;recordedAt:string}>;registers:Array<{registerType:string;serialNumber:string;transactionDate:string;patientName:string;batchNumber:string;quantitySupplied:number}>};
export function VendorOperationsCenter(){
  const [data,setData]=useState<VendorOps|null>(null),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=async()=>{setError("");const response=await authenticatedFetch("/api/vendor/operations",{cache:"no-store"});const payload=await response.json() as VendorOps&{error?:string};if(!response.ok){setData(null);setError(payload.error||"Sign in as a vendor to load operations");return;}setData(payload);};useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load();},[]);
  const submit=async(event:FormEvent<HTMLFormElement>,action:string)=>{event.preventDefault();setError("");setMessage("");const values=Object.fromEntries(new FormData(event.currentTarget));const response=await authenticatedFetch("/api/vendor/operations",{method:"POST",body:JSON.stringify({action,...values})});const payload=await response.json() as {error?:string;action?:string;creditNote?:string;debitNoteNumber?:string};if(!response.ok){setError(payload.error||"Operation failed");return;}setMessage(payload.creditNote?`Return completed. Credit note ${payload.creditNote}.`:payload.debitNoteNumber?`Supplier return completed. Debit note ${payload.debitNoteNumber}.`:payload.action||"Operation saved.");await load();};
  const money=(paise:number)=>`₹${((paise||0)/100).toLocaleString("en-IN",{minimumFractionDigits:2})}`;
  return <div className="portal-stack"><Notice error={error} message={message}/>{data&&<><div className="portal-metrics"><article><span className="amber"><Boxes size={20}/></span><div><small>Low / zero stock</small><strong>{data.summary.lowStock}</strong><em>Reorder controls active</em></div></article><article><span className="red"><AlertTriangle size={20}/></span><div><small>Near expiry</small><strong>{data.summary.nearExpiry}</strong><em>Next 90 days</em></div></article><article><span className="blue"><Thermometer size={20}/></span><div><small>Quarantined</small><strong>{data.summary.quarantined}</strong><em>Blocked from sale</em></div></article><article><span className="green"><Landmark size={20}/></span><div><small>Total sales</small><strong>{money(data.summary.onlineSalesPaise+data.summary.offlineSalesPaise)}</strong><em>Online + offline</em></div></article></div>
    <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">COUNTER BILLING</span><h2>Record an offline sale</h2><p>FEFO, expiry, quarantine, GST invoice and atomic stock controls are enforced server-side.</p></div></div><form className="portal-form-grid" onSubmit={event=>void submit(event,"offline_sale")}><label className="portal-field"><span>Customer name</span><input name="customerName" placeholder="Walk-in customer"/></label><label className="portal-field"><span>Phone</span><input maxLength={10} name="customerPhone" pattern="[0-9]{10}"/></label><label className="portal-field"><span>Medicine batch *</span><select name="inventoryId" required>{data.inventory.filter(row=>row.quarantineStatus==="available"&&row.quantity>0&&row.expiryDate>=new Date().toISOString().slice(0,10)).map(row=><option key={row.id} value={row.id}>{row.productName} · {row.batchNumber} · {row.quantity} available</option>)}</select></label><label className="portal-field"><span>Quantity *</span><input min="1" name="quantity" required type="number"/></label><label className="portal-field"><span>Payment mode</span><select name="paymentMode"><option value="cash">Cash</option><option value="upi">UPI</option><option value="card">Card</option><option value="credit">Credit</option></select></label><button className="portal-primary" type="submit">Save sale & issue GST invoice</button></form></section>
    <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">LIVE CONTROL CENTRE</span><h2>Stock, expiry and sales reporting</h2><p>Tenant-filtered alerts, batch traceability and channel totals from live records.</p></div><button className="portal-outline" onClick={()=>void load()} type="button"><RefreshCw size={15}/> Refresh</button></div><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Stock</th><th>Control</th></tr></thead><tbody>{data.alerts.slice(0,30).map(row=><tr key={row.id}><td><strong>{row.productName}</strong></td><td>{row.batchNumber}</td><td>{row.expiryDate}</td><td>{row.quantity}</td><td><span className={`portal-status ${row.alertType==="near_expiry"?"amber":"red"}`}>{row.alertType.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div></section>
    <div className="portal-split"><section className="portal-panel"><h2>Cold-chain log</h2><form className="portal-form-grid one" onSubmit={event=>void submit(event,"temperature")}><label className="portal-field"><span>Inventory batch</span><select name="inventoryId" required>{data.inventory.filter(row=>row.coldChainRequired).map(row=><option key={row.id} value={row.id}>{row.productName} · {row.batchNumber}</option>)}</select></label><label className="portal-field"><span>Storage location</span><input name="storageLocation" required placeholder="Cold room / refrigerator"/></label><label className="portal-field"><span>Temperature °C</span><input name="temperatureCelsius" required step="0.1" type="number"/></label><button className="portal-primary" type="submit"><Thermometer size={15}/> Record & enforce</button></form><div className="history-cards">{data.temperatures.slice(0,5).map(row=><article key={row.id}><span><Thermometer size={18}/></span><div><strong>{(row.temperatureCelsiusX10/10).toFixed(1)}°C · {row.productName||"Storage"}</strong><small>{row.batchNumber||"Location log"}</small><em>{row.withinRange?"Within range":"Excursion — quarantined"}</em></div></article>)}</div></section>
      <section className="portal-panel"><h2>Return & credit note</h2><form className="portal-form-grid one" onSubmit={event=>void submit(event,"return")}><label className="portal-field"><span>Sale channel</span><select name="sourceType"><option value="online">Online order</option><option value="offline">Offline sale</option></select></label><label className="portal-field"><span>Source order / sale ID</span><input name="sourceId" required type="number"/></label><label className="portal-field"><span>Inventory batch</span><select name="inventoryId" required>{data.inventory.map(row=><option key={row.id} value={row.id}>{row.productName} · {row.batchNumber}</option>)}</select></label><label className="portal-field"><span>Quantity</span><input min="1" name="quantity" required type="number"/></label><label className="portal-field"><span>Condition</span><select name="condition"><option value="sealed">Sealed and saleable</option><option value="damaged">Damaged</option><option value="expired">Expired</option></select></label><label className="portal-field"><span>Reason</span><textarea name="reason" required rows={2}/></label><button className="portal-secondary" type="submit">Issue credit note</button></form><div className="history-cards">{data.returns.slice(0,5).map(row=><article key={row.returnNumber}><span><FileCheck2 size={18}/></span><div><strong>{row.creditNoteNumber}</strong><small>{row.returnNumber} · {money(row.refundPaise)}</small><em>{row.reason}</em></div></article>)}</div></section></div>
    <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">SUPPLIER RETURN</span><h2>Return damaged or expired stock to stockist</h2><p>Validates the original purchase, prevents excess returns, deducts batch stock and posts a debit note.</p></div></div><form className="portal-form-grid" onSubmit={event=>void submit(event,"supplier_return")}><label className="portal-field"><span>Purchase item *</span><select name="purchaseOrderItemId" required>{data.returnablePurchases.filter(row=>row.currentQuantity>0&&row.purchasedQuantity>row.returnedQuantity).map(row=><option key={row.purchaseOrderItemId} value={row.purchaseOrderItemId}>{row.purchaseNumber} · {row.supplierName} · {row.productName} · {row.batchNumber}</option>)}</select></label><label className="portal-field"><span>Quantity *</span><input min="1" name="quantity" required type="number"/></label><label className="portal-field wide"><span>Return reason *</span><textarea name="reason" required rows={2} placeholder="Expired, damaged in storage, supplier recall or quality defect"/></label><button className="portal-primary" type="submit">Return stock & issue debit note</button></form><div className="history-cards">{data.supplierReturns.slice(0,8).map(row=><article key={row.returnNumber}><span><FileCheck2 size={18}/></span><div><strong>{row.debitNoteNumber} · {row.supplierName}</strong><small>{row.returnNumber} · {row.purchaseNumber} · {money(row.totalPaise)}</small><em>{row.reason}</em></div></article>)}</div></section>
    <section className="portal-panel"><div className="portal-panel-heading"><div><h2>Statutory register</h2><p>H1 and prescription transaction evidence retained with pharmacist and batch traceability.</p></div></div><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Register</th><th>Serial</th><th>Date</th><th>Patient</th><th>Batch</th><th>Qty</th></tr></thead><tbody>{data.registers.map(row=><tr key={`${row.registerType}-${row.serialNumber}`}><td>{row.registerType}</td><td>{row.serialNumber}</td><td>{row.transactionDate}</td><td>{row.patientName}</td><td>{row.batchNumber}</td><td>{row.quantitySupplied}</td></tr>)}</tbody></table></div></section></>}
  </div>;
}

type AdminOps={summary:{vendors:number;verifiedVendors:number;products:number;orders:number;onlineSalesPaise:number;offlineSalesPaise:number;expensesPaise:number;activeDeliveries:number};categories:Array<{id:number;name:string;status:string}>;stores:Array<{id:number;businessName:string;ownerName:string;complianceStatus:string;latitude:string;longitude:string}>;expenses:Array<{id:number;purpose:string;expenseHead:string;amountPaise:number;expenseDate:string}>;deliveries:Array<{orderId:number;orderNumber:string;customerName:string;businessName:string;deliveryMethod:string;deliveryStatus:string;agentName:string|null;assignmentStatus:string|null}>;deliveryAgents:Array<{id:number;name:string;vehicleType:string;vehicleNumber:string;availabilityStatus:string;activeAssignments:number}>;governance:{consentEvents:number;auditEvents:number;retentionPolicies:number;openBreaches:number;verifiedBackups:number;irnInvoices:number;taxInvoices:number};eInvoice:{ready:boolean;message:string}};
export function AdminOperationsCenter({mode}:{mode:"overview"|"categories"|"accounts"|"reports"}){
  const [data,setData]=useState<AdminOps|null>(null),[error,setError]=useState(""),[message,setMessage]=useState("");const load=async()=>{setError("");const response=await authenticatedFetch("/api/admin/operations",{cache:"no-store"});const payload=await response.json() as AdminOps&{error?:string};if(!response.ok){setError(payload.error||"Admin operations are unavailable");return;}setData(payload);};useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load();},[]);
  const submit=async(event:FormEvent<HTMLFormElement>,action:string)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const response=await authenticatedFetch("/api/admin/operations",{method:"POST",body:JSON.stringify({action,...values})});const payload=await response.json() as {error?:string};if(!response.ok){setError(payload.error||"Admin update failed");return;}setMessage("Admin record saved with double-entry and audit evidence where applicable.");event.currentTarget.reset();await load();};const money=(value:number)=>`₹${((value||0)/100).toLocaleString("en-IN",{minimumFractionDigits:2})}`;
  const processReminders=async()=>{setError("");const response=await authenticatedFetch("/api/admin/reminders/process",{method:"POST"});const payload=await response.json() as {error?:string;processed?:{total:number;refills:number;pills:number}};if(!response.ok){setError(payload.error||"Reminder processing failed");return;}setMessage(`${payload.processed?.total??0} reminders processed (${payload.processed?.refills??0} refills and ${payload.processed?.pills??0} pill schedules).`);await load();};
  if(!data)return <section className="portal-panel"><div className="portal-panel-heading"><div><h2>Live administration</h2><p>An active administrator account is required.</p></div><button className="portal-outline" onClick={()=>void load()} type="button"><RefreshCw size={15}/> Retry</button></div><Notice error={error} message={message}/></section>;
  if(mode==="categories")return <section className="portal-panel"><Notice error={error} message={message}/><div className="portal-panel-heading"><div><span className="portal-kicker">LIVE CATEGORY MASTER</span><h2>Product categories</h2></div></div><form className="portal-form-grid" onSubmit={event=>void submit(event,"category")}><label className="portal-field"><span>Name *</span><input name="name" required/></label><label className="portal-field"><span>Status</span><select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="portal-primary" type="submit"><Plus size={15}/> Add category</button></form><div className="category-admin-grid">{data.categories.map(row=><article key={row.id}><span><Boxes size={18}/></span><strong>{row.name}</strong><em>{row.status}</em></article>)}</div></section>;
  if(mode==="accounts")return <div className="portal-split"><section className="portal-panel"><h2>Record expense</h2><Notice error={error} message={message}/><form className="portal-form-grid one" onSubmit={event=>void submit(event,"expense")}><label className="portal-field"><span>Purpose</span><input name="purpose" required/></label><label className="portal-field"><span>Expense head</span><input name="expenseHead" required/></label><label className="portal-field"><span>Amount ₹</span><input min="0.01" name="amount" required step="0.01" type="number"/></label><label className="portal-field"><span>Date</span><input name="expenseDate" required type="date"/></label><label className="portal-field"><span>Payment mode</span><select name="paymentMode"><option>Bank transfer</option><option>UPI</option><option>Cash</option></select></label><button className="portal-primary" type="submit">Post double-entry expense</button></form></section><section className="portal-panel"><h2>Expense ledger</h2><div className="ledger-list">{data.expenses.map(row=><article key={row.id}><span>{row.purpose}<small>{row.expenseHead} · {row.expenseDate}</small></span><strong>{money(row.amountPaise)}</strong></article>)}</div></section></div>;
  return <div className="portal-stack"><Notice error={error} message={message}/><div className="portal-metrics"><article><span className="green"><CheckCircle2 size={20}/></span><div><small>Verified pharmacies</small><strong>{data.summary.verifiedVendors}/{data.summary.vendors}</strong><em>Licence controls</em></div></article><article><span className="blue"><Boxes size={20}/></span><div><small>Active products</small><strong>{data.summary.products.toLocaleString("en-IN")}</strong><em>Recovered catalogue</em></div></article><article><span className="amber"><Truck size={20}/></span><div><small>Active deliveries</small><strong>{data.summary.activeDeliveries}</strong><em>Assignment tracking</em></div></article><article><span className="red"><Landmark size={20}/></span><div><small>Net sales less expense</small><strong>{money(data.summary.onlineSalesPaise+data.summary.offlineSalesPaise-data.summary.expensesPaise)}</strong><em>Operational position</em></div></article></div>
    <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">DELIVERY DISPATCH</span><h2>Assign URMED delivery agents</h2><p>Only available riders can be assigned. Rider tracking is restricted to their own assignments.</p></div></div><form className="portal-form-grid" onSubmit={event=>void submit(event,"assign_delivery")}><label className="portal-field"><span>Ready URMED order</span><select name="orderId" required>{data.deliveries.filter(row=>row.deliveryMethod==="urmed"&&!row.agentName&&row.deliveryStatus==="ready_for_pickup").map(row=><option key={row.orderId} value={row.orderId}>{row.orderNumber} · {row.customerName} · {row.businessName}</option>)}</select></label><label className="portal-field"><span>Available rider</span><select name="agentId" required>{data.deliveryAgents.filter(row=>["available","online"].includes(row.availabilityStatus)).map(row=><option key={row.id} value={row.id}>{row.name} · {row.vehicleNumber} · {row.activeAssignments} active</option>)}</select></label><button className="portal-primary" type="submit">Assign rider</button></form><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Order</th><th>Customer</th><th>Pharmacy</th><th>Rider</th><th>Status</th></tr></thead><tbody>{data.deliveries.slice(0,30).map(row=><tr key={row.orderId}><td><strong>{row.orderNumber}</strong></td><td>{row.customerName}</td><td>{row.businessName}</td><td>{row.agentName||"Unassigned"}</td><td><span className="portal-status amber">{row.deliveryStatus.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div></section>
    <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">GOVERNANCE EVIDENCE</span><h2>Compliance and operational readiness</h2><p>Live counts for consent, audit, retention, breach, backup and invoice controls.</p></div><div className="panel-actions"><button className="portal-outline" onClick={()=>void processReminders()} type="button"><BellRing size={15}/> Process due reminders</button><button className="portal-outline" onClick={()=>void load()} type="button"><RefreshCw size={15}/> Refresh</button></div></div><div className="recovery-counts"><article><ShieldCheck size={19}/><span><small>Consent events</small><strong>{data.governance.consentEvents}</strong></span></article><article><FileCheck2 size={19}/><span><small>Audit events</small><strong>{data.governance.auditEvents}</strong></span></article><article><Landmark size={19}/><span><small>Retention policies</small><strong>{data.governance.retentionPolicies}</strong></span></article><article><Truck size={19}/><span><small>Tracked deliveries</small><strong>{data.summary.activeDeliveries}</strong></span></article></div><div className={`portal-note ${data.eInvoice.ready?"":"warning"}`}><FileCheck2 size={18}/><span><strong>E-invoice / IRN connector</strong><small>{data.eInvoice.message}. {data.governance.irnInvoices} of {data.governance.taxInvoices} invoices currently have IRNs.</small></span></div></section></div>;
}

type DeliveryData={profile:{name:string;email:string};agent:{vehicleType:string;vehicleNumber:string;availabilityStatus:string;currentLatitude:string;currentLongitude:string};assignments:Array<{assignmentId:number;orderId:number;orderNumber:string;customerName:string;deliveryAddress:string;deliveryStatus:string;paymentMethod:string;paymentStatus:string;totalPaise:number;businessName:string;pickupAddress:string}>};
export function DeliveryOperationsCenter(){
  const [data,setData]=useState<DeliveryData|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[latitude,setLatitude]=useState("17.4318"),[longitude,setLongitude]=useState("78.4073");
  const [liveTracking,setLiveTracking]=useState(false),[accuracy,setAccuracy]=useState<number|null>(null),[lastFix,setLastFix]=useState("");
  const lastSentAt=useRef(0);
  const load=async()=>{const response=await authenticatedFetch("/api/delivery",{cache:"no-store"});const payload=await response.json() as DeliveryData&{error?:string};if(!response.ok){setData(null);setError(payload.error||"Sign in as a delivery agent");return;}setData(payload);if(payload.agent.currentLatitude&&payload.agent.currentLongitude){setLatitude(payload.agent.currentLatitude);setLongitude(payload.agent.currentLongitude);}setError("");};
  useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
    void load();},[]);
  useEffect(()=>{
    if(!liveTracking)return;
    if(!navigator.geolocation)return;
    const watchId=navigator.geolocation.watchPosition((position)=>{
      const nextLatitude=position.coords.latitude.toFixed(6),nextLongitude=position.coords.longitude.toFixed(6);
      setLatitude(nextLatitude);setLongitude(nextLongitude);setAccuracy(Math.round(position.coords.accuracy));setLastFix(new Date().toLocaleTimeString("en-IN"));
      const now=Date.now();if(now-lastSentAt.current<15000)return;lastSentAt.current=now;
      void authenticatedFetch("/api/delivery",{method:"POST",body:JSON.stringify({availabilityStatus:"online",latitude:nextLatitude,longitude:nextLongitude,source:"gps_watch"})}).then(async(response)=>{
        if(!response.ok){const payload=await response.json() as {error?:string};throw new Error(payload.error||"Live location update failed");}
      }).catch((reason)=>setError(reason instanceof Error?reason.message:"Live location update failed"));
    },(reason)=>{setError(reason.code===reason.PERMISSION_DENIED?"Location permission was denied. Enable it in browser settings to use live rider tracking.":"Live GPS could not obtain a position.");setLiveTracking(false);},{enableHighAccuracy:true,timeout:20000,maximumAge:5000});
    return()=>navigator.geolocation.clearWatch(watchId);
  },[liveTracking]);
  const availability=async(value:string)=>{const response=await authenticatedFetch("/api/delivery",{method:"POST",body:JSON.stringify({availabilityStatus:value,latitude,longitude})});const payload=await response.json() as {error?:string};if(!response.ok){setError(payload.error||"Availability update failed");return;}setMessage(`Rider marked ${value}.`);await load();};
  const toggleLiveTracking=()=>{if(liveTracking){setLiveTracking(false);return;}if(!navigator.geolocation){setError("This browser does not support live GPS tracking");return;}setError("");setLiveTracking(true);};
  const advance=async(orderId:number,status:string)=>{const response=await authenticatedFetch(`/api/orders/${orderId}/tracking`,{method:"POST",body:JSON.stringify({status,latitude,longitude,note:`Delivery agent updated order to ${status.replaceAll("_"," ")}`})});const payload=await response.json() as {error?:string};if(!response.ok){setError(payload.error||"Tracking update failed");return;}setMessage(`Delivery updated to ${status.replaceAll("_"," ")}.`);await load();};
  const next=nextRiderAction;
  if(!data)return <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">RIDER WORKSPACE</span><h2>Delivery data unavailable</h2><p>The active delivery session could not load its assignment-scoped workspace.</p></div><button className="portal-outline" onClick={()=>void load()} type="button"><RefreshCw size={15}/> Retry</button></div><Notice error={error} message={message}/></section>;
  return <div className="portal-stack"><Notice error={error} message={message}/><section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">RIDER WORKSPACE</span><h2>{data.profile.name}</h2><p>{data.agent.vehicleType} · {data.agent.vehicleNumber} · {liveTracking?"live GPS online":data.agent.availabilityStatus}</p></div></div><div className="portal-form-grid one"><GeoLocationPicker label="Rider's current position" latitude={latitude} longitude={longitude} onChange={(location)=>{setLatitude(location.latitude);setLongitude(location.longitude);setAccuracy(location.accuracy?Math.round(location.accuracy):accuracy);}}/><div className={`live-gps-status ${liveTracking?"active":""}`}><span><strong>{liveTracking?"Live GPS sharing is active":"Live GPS sharing is off"}</strong><small>{accuracy!==null?`Accuracy about ${accuracy} m${lastFix?` · last fix ${lastFix}`:""}`:"Start tracking only while on duty."}</small></span><button className={liveTracking?"portal-outline":"portal-primary"} onClick={toggleLiveTracking} type="button">{liveTracking?"Stop live GPS":"Start live GPS"}</button></div><div className="panel-actions"><button onClick={()=>void availability("available")} type="button">Save & mark available</button><button onClick={()=>{setLiveTracking(false);void availability("offline");}} type="button">Go offline</button></div></div></section><section className="portal-panel"><div className="portal-panel-heading"><div><h2>My assigned deliveries</h2><p>Only orders assigned to this rider are visible and actionable. Delivery events use the latest GPS fix.</p></div><button className="portal-outline" onClick={()=>void load()} type="button"><RefreshCw size={15}/> Refresh</button></div><div className="history-cards">{data.assignments.map(row=><article key={row.assignmentId}><span><Truck size={19}/></span><div><strong>{row.orderNumber} · {row.customerName}</strong><small>{row.businessName} → {row.deliveryAddress}</small><em>{row.deliveryStatus.replaceAll("_"," ")} · ₹{(row.totalPaise/100).toFixed(2)} · {row.paymentMethod.toUpperCase()}</em></div>{next(row.deliveryStatus)&&<button onClick={()=>void advance(row.orderId,next(row.deliveryStatus))} type="button">Mark {next(row.deliveryStatus).replaceAll("_"," ")}</button>}</article>)}</div></section></div>;
}
