"use client";
import { useCallback, useState } from "react";
import { authenticatedFetch } from "./marketplace-client";
type Price = { id:number; salePricePaise:number; mrpPaise:number; effectiveFrom:string; reason:string };
type Data = { prices:Price[]; barcodes:Array<{id:number;code:string;symbology:string;status:string}> };
export function PricingGovernanceCenter({ admin = false }: { admin?: boolean }) {
  const [inventoryId,setInventoryId]=useState(""),[data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{if(!inventoryId)return;const response=await authenticatedFetch(`${admin?"/api/admin/pricing":"/api/vendor/pricing"}?inventoryId=${inventoryId}`,{cache:"no-store"});const payload=await response.json() as Data&{error?:string};if(!response.ok){setError(payload.error??"Pricing governance unavailable");return;}setData(payload);setError("");},[admin,inventoryId]);
  const approve=async(id:number)=>{const response=await authenticatedFetch("/api/admin/pricing",{method:"PATCH",body:JSON.stringify({id,action:"barcode_approve"})});const payload=await response.json() as {error?:string};if(!response.ok){setError(payload.error??"Pricing action failed");return;}setMessage("Barcode approved");await load();};
  return <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">PRICING GOVERNANCE</span><h2>Effective prices and GTIN records</h2><p>Prices are effective-dated and MRP-enforced. NPPA ceilings remain disabled until an approved policy is configured.</p></div></div><div className="portal-form-grid"><label className="portal-field"><span>Inventory batch</span><input value={inventoryId} onChange={e=>setInventoryId(e.target.value)} placeholder="Inventory ID" /></label><button className="portal-outline" onClick={()=>void load()} type="button">Load</button></div>{error&&<p className="auth-message error">{error}</p>}{message&&<p className="auth-message success">{message}</p>}{data&&<><h3>Price history</h3><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Effective</th><th>Sale</th><th>MRP</th><th>Reason</th></tr></thead><tbody>{data.prices.map(row=><tr key={row.id}><td>{row.effectiveFrom}</td><td>₹{(row.salePricePaise/100).toFixed(2)}</td><td>₹{(row.mrpPaise/100).toFixed(2)}</td><td>{row.reason}</td></tr>)}</tbody></table></div><h3>GTIN / barcode records</h3><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Code</th><th>Symbology</th><th>Status</th>{admin&&<th>Action</th>}</tr></thead><tbody>{data.barcodes.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.symbology}</td><td>{row.status}</td>{admin&&row.status==="pending"&&<td><button onClick={()=>void approve(row.id)} type="button">Approve</button></td>}</tr>)}</tbody></table></div></>}</section>;
}
