"use client";

import { useEffect, useState } from "react";
import { authenticatedFetch } from "./marketplace-client";

type Branch = { id: number; branchCode: string; name: string; status: string; address: string; latitude: string; longitude: string; publicLabel: string; publicAddress: string; publicLatitude: string; publicLongitude: string; publicLocationStatus: string; pickupEnabled: number; serviceEnabled: number; serviceRadiusKm: number; isPrimary: number };

export function VendorBranchManager() {
  const [branches, setBranches] = useState<Branch[]>([]);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState({ branchCode: "", name: "", address: "", latitude: "", longitude: "", pickupEnabled: true, serviceEnabled: true, serviceRadiusKm: "5", publicLabel: "", publicAddress: "", publicLatitude: "", publicLongitude: "", publishPublicLocation: false });
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const load = async () => { const response = await authenticatedFetch("/api/vendor/branches", { cache: "no-store" }); if (response.ok) setBranches(((await response.json()) as { branches: Branch[] }).branches); };
  useEffect(() => {
    // Loading is an external request; defer the state update until the promise settles.
    void Promise.resolve().then(() => load());
  }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setMessage(""); const response = await authenticatedFetch("/api/vendor/branches", { method: "POST", body: JSON.stringify({ ...form, ...(editingId === null ? {} : { id: editingId }) }) }); const body = await response.json() as { error?: string; branches?: Branch[] }; if (!response.ok) { setError(body.error ?? "Branch could not be saved"); return; } setBranches(body.branches ?? []); setEditingId(null); setForm({ branchCode: "", name: "", address: "", latitude: "", longitude: "", pickupEnabled: true, serviceEnabled: true, serviceRadiusKm: "5", publicLabel: "", publicAddress: "", publicLatitude: "", publicLongitude: "", publishPublicLocation: false }); setMessage("Branch saved. Inventory and checkout remain scoped to the selected branch."); };
  const edit = (branch: Branch) => { setEditingId(branch.id); setForm({ branchCode: branch.branchCode, name: branch.name, address: branch.address, latitude: branch.latitude, longitude: branch.longitude, pickupEnabled: Boolean(branch.pickupEnabled), serviceEnabled: Boolean(branch.serviceEnabled), serviceRadiusKm: String(branch.serviceRadiusKm), publicLabel: branch.publicLabel, publicAddress: branch.publicAddress, publicLatitude: branch.publicLatitude, publicLongitude: branch.publicLongitude, publishPublicLocation: branch.publicLocationStatus === "published" }); setMessage(""); setError(""); };
  const toggle = async (branch: Branch) => { const action = branch.status === "active" ? "deactivate" : "activate"; const response = await authenticatedFetch("/api/vendor/branches", { method: "POST", body: JSON.stringify({ action, id: branch.id }) }); const body = await response.json() as { error?: string; branches?: Branch[] }; if (!response.ok) setError(body.error ?? "Branch status could not be changed"); else setBranches(body.branches ?? []); };
  return <section className="portal-panel"><div className="portal-panel-heading"><div><span className="portal-kicker">OPERATIONAL BRANCHES</span><h2>Pharmacy branches</h2><p>Each branch owns its stock and customer-facing pickup/service point. Legal coordinates stay private.</p></div></div>{message && <div className="auth-message success">{message}</div>}{error && <div className="auth-message error">{error}</div>}<form className="portal-form-grid" onSubmit={save}>{(["branchCode", "name", "address", "latitude", "longitude", "publicLabel", "publicAddress", "publicLatitude", "publicLongitude"] as const).map((key) => <label className="portal-field" key={key}><span>{key.replaceAll(/([A-Z])/g, " $1").replace(/^./, (value) => value.toUpperCase())}{["branchCode", "name", "address"].includes(key) ? " *" : ""}</span><input required={["branchCode", "name", "address"].includes(key)} onChange={(event) => setForm({ ...form, [key]: event.target.value })} value={form[key]} /></label>)}<label className="portal-field"><span>Service radius (km)</span><input min="1" max="50" onChange={(event) => setForm({ ...form, serviceRadiusKm: event.target.value })} type="number" value={form.serviceRadiusKm} /></label><label className="portal-field"><span><input checked={form.pickupEnabled} onChange={(event) => setForm({ ...form, pickupEnabled: event.target.checked })} type="checkbox" /> Pickup enabled</span><span><input checked={form.serviceEnabled} onChange={(event) => setForm({ ...form, serviceEnabled: event.target.checked })} type="checkbox" /> Delivery enabled</span><span><input checked={form.publishPublicLocation} onChange={(event) => setForm({ ...form, publishPublicLocation: event.target.checked })} type="checkbox" /> Publish customer-facing location</span></label><button className="portal-primary" type="submit">{editingId === null ? "Create branch" : "Save branch"}</button>{editingId !== null && <button className="portal-secondary" onClick={() => setEditingId(null)} type="button">Cancel edit</button>}</form><div className="live-list">{branches.map((branch) => <article key={branch.id}><div><strong>{branch.name} · {branch.branchCode}</strong><small>{branch.isPrimary ? "Primary · " : ""}{branch.status} · {branch.publicLocationStatus === "published" ? "Public location published" : "Location draft"}</small></div><div>{<button className="portal-secondary" onClick={() => edit(branch)} type="button">Edit</button>}{!branch.isPrimary && <button className="portal-secondary" onClick={() => void toggle(branch)} type="button">{branch.status === "active" ? "Deactivate" : "Activate"}</button>}</div></article>)}</div></section>;
}
